# Configures rkt tests at Travis CI (https://travis-ci.org).

language: go
sudo: required
dist: trusty

go:
  - 1.5.3
  - 1.6

addons:
  apt:
    packages:
    - cpio
    - realpath
    - squashfs-tools
    - build-essential
    - libacl1-dev
    - libsystemd-journal-dev

install:
  -

script:
 - ./autogen.sh
 # Build host and fly to ensure we build stage1 init. We don't build everything
 # to avoid downloading large images.
 - ./configure --with-stage1-flavors=host,fly --enable-tpm=auto
 - make unit-check
